stages: 
  - build
jobs:
  include:
    - stage: build
      language: node_js
      node_js:
        - node
      install:
        - cd host
        - npm ci
      script:
        - npm run build
      name: Build Host Server
    - stage: build
      language: node_js
      node_js:
        - node
      install:
        - cd host/web
        - npm ci
      script:
        - npm run build
      name: Build Host Web
    - stage: build
      language: node_js
      node_js:
        - node
      install:
        - cd components/server
        - npm ci
      script:
        - npm run build
      name: Build Server Components